# Generated by Django 3.0.5 on 2020-05-07 04:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200506_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_modifed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='Document of Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Post Title'),
        ),
    ]
