# Generated by Django 3.0.5 on 2020-05-10 14:14

import django.core.validators
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200509_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), posts.models.validate_document_size], verbose_name='Document of Post'),
        ),
    ]
