# Generated by Django 3.0.5 on 2020-05-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20200524_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttagextended',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='tag_count'),
        ),
        migrations.AddField(
            model_name='posttagextended',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posttagextended',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
