# Generated by Django 3.0.5 on 2020-05-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20200524_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttagextended',
            name='creator',
        ),
    ]
