# Generated by Django 3.0.5 on 2020-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_posttagextended_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttagextended',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='tag_count'),
        ),
    ]
