# Generated by Django 3.0.5 on 2020-05-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_followconnection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowConnection',
            new_name='UserConnection',
        ),
    ]
