# Generated by Django 3.0.5 on 2020-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200510_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('email_verified', 'User email is verified')]},
        ),
        migrations.AlterModelOptions(
            name='userconnection',
            options={'ordering': ['-timestamp']},
        ),
    ]
