# Generated by Django 3.0.5 on 2020-05-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200511_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('verified', 'User verified')]},
        ),
    ]
