# Generated by Django 3.0.5 on 2020-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200511_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='profile_pictures/default_thumbnail.jpg', upload_to='profile_pictures/thumbs', verbose_name='User Avatar'),
        ),
    ]
